services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: iced-tea
      POSTGRES_PASSWORD: iced-tea
      POSTGRES_DB: iced-tea
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 5s
      retries: 10
  # backend:
  #   container_name: ice-tea-be
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/usr/src/app
  #   env_file:
  #     - ./backend/.env

#  frontend:
#    container_name: ice-tea-fe
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/usr/src/app
#      - /usr/src/app/node_modules
